// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4LeggedFriendsServer.Data;

#nullable disable

namespace _4LeggedFriendsServer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_4LeggedFriendsServer.Models.ContactTypeEntity", b =>
                {
                    b.Property<int>("IdContactType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContactType"), 1L, 1);

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdContactType");

                    b.ToTable("ContactTypes");
                });

            modelBuilder.Entity("_4LeggedFriendsServer.Models.EventTypeEntity", b =>
                {
                    b.Property<int>("IdEventType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEventType"), 1L, 1);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdEventType");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("_4LeggedFriendsServer.Models.PetTypeEntity", b =>
                {
                    b.Property<int>("IdPetType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPetType"), 1L, 1);

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PetTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdPetType");

                    b.ToTable("PetTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
